### ISSUE TITLE
Update to Elixir 1.3.2

### ISSUE THREAD

**Issue by craig-day** [bitwalker/alpine-elixir-phoenix#1]
Hi @bitwalker,  first thanks so much for this awesome base image, made dockerizing my phoenix app super simple.

Can we update this to Erlang/OTP 19 and Elixir 1.3.2? There are some fun new features from 1.3 that I would love to use.

**Comment by bitwalker** [comment]
Sure thing, I'll do it first thing in the morning!

**Comment by bitwalker** [comment]
Currently Alpine only has 1.3.1 in it's package repository, but I'm watching for 1.3.2. The latest release of this image has 1.3.1 in any case, so I'm going to close this for now.
