### ISSUE TITLE
Example error?

### ISSUE THREAD

**Issue by simonh1000** [bitwalker/alpine-elixir-phoenix#10]
So I am completely new (this is my absolute first hour with docker), but I was thrown by the example. As things stand it reads:
```
# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

# Same with npm deps
ADD package.json package.json
RUN npm install

ADD . .
```

This seems to run deps.get before adding the source files. As a result when it comes to compiling the app, the dependencies are not available resulting in hex errors

I am currently moving ADD . . to after the other ADD line

**Comment by bitwalker** [comment]
It adds `mix.exs` and `mix.lock` prior to fetching and compiling just the deps, no other files are required. What is the error you are seeing?

The reason for this is to cache the deps and the compilation artifacts and only regenerate them if needed, so if you have regular changes, the layers which need to be updated are smaller.
