### ISSUE TITLE
Update instructions for Phoenix 1.3

### ISSUE THREAD

**Issue by ggerico** [bitwalker/alpine-elixir-phoenix#13]
You might modify the "Extending for your own application" part in the readme to reflect the new directory tree of Phoenix 1.3. You would have to change the instructions related to brunch and node.

**Comment by bitwalker** [comment]
Would you be willing to open a PR with the changes? I'm not actively working on any Phoenix-based projects at the moment, so I'd rather have someone using the image and working with the latest provide the correct instructions. I unfortunately don't have much time to review and test the changes at the moment.
