### ISSUE TITLE
node_modules: is it needed in the file image?

### ISSUE THREAD

**Issue by mbana** [bitwalker/alpine-elixir-phoenix#28]
I think Node.js is just required to build the final application right? It is not required in the final image, nor is the `node_modules` dir...

If so, would be nice to remove these.

**Comment by bitwalker** [comment]
You should use `alpine-elixir` or `alpine-erlang` for deployment, this image is intended for builds and testing, where you want all of the development tooling available. `alpine-erlang` is specifically designed for releases, and `alpine-elixir` can be used for that purpose as well, though it contains an Elixir installation, so technically has extra cruft you would not need in a release image.

**Comment by KristerV** [comment]
hey @mbana can you share your Dockerfile for local development? I'm having a bunch of trouble..
