### ISSUE TITLE
Publish new version on dockerhub

### ISSUE THREAD

**Issue by outsmartin** [bitwalker/alpine-elixir-phoenix#36]
Hey, thanks for updating the repo.

Unfortunately it is not published yet to dockerhub.
Would it make sense to use the https://docs.docker.com/docker-hub/github/ integration so you don't have to worry about it any more?

In any case thanks for keeping it up to date and providing the images 👍

**Comment by bitwalker** [comment]
Ah, I have automated builds for `alpine-erlang` and `alpine-elixir`, but not this one, I've set that up and triggered builds, there should be images up soon.
