### ISSUE TITLE
Hex and Rebar (v1.7.3)

### ISSUE THREAD

**Issue by daveli** [bitwalker/alpine-elixir-phoenix#37]
It seems that in the 1.7.3 release Hex and Rebar don't seem to work anymore: "Could not find Hex, which is needed to build dependency (x)". Both are however included inside https://github.com/bitwalker/alpine-elixir/blob/master/Dockerfile#L23.
Running the code using the `alpine-elixir` Docker image directly seems to work. After it being cached by Docker using `alpine-elixir-phoenix` somehow works magicly... 
To reproduce the error build the Docker image without any cache.

As a temp fix you can add back the Hex and Rebar install code to your Dockerfile:

```
FROM bitwalker/alpine-elixir-phoenix:1.7.3

RUN mix local.hex --force && \
    mix local.rebar --force

...

RUN mix do deps.get, deps.compile

...
```

**Comment by bitwalker** [comment]
@daveli Can you submit a PR which adds those back? I'll get it merged and push an updated 1.7.3 image

**Comment by Razzeee** [comment]
Seems to be fixed in latest but not in 1.7.3

**Comment by Nicd** [comment]
Still having this issue.

**Comment by Razzeee** [comment]
did you reference latest?

**Comment by Nicd** [comment]
I used `image: bitwalker/alpine-elixir-phoenix:1.7.3`

Should I use `image: bitwalker/alpine-elixir-phoenix:latest`? I'm not too used to these things.

**Comment by Razzeee** [comment]
do latest or without `image: bitwalker/alpine-elixir-phoenix` it's not ideal to not pin these, but this is the best we can do for now.

**Comment by bitwalker** [comment]
Pushing a new version today, so closing this
