### ISSUE TITLE
Can't deploy with Zeit now

### ISSUE THREAD

**Issue by tlvenn** [bitwalker/alpine-elixir-phoenix#4]
Hi @bitwalker,

I am trying to deploy a small phoenix app to Zeit (https://zeit.co/) using their Dockerfile support.
The image is properly built however when the container starts, there is an error:

```
Could not find Hex, which is needed to build dependency :phoenix
** (Mix) Could not find an SCM for dependency :phoenix from SnsRouter.Mixfile
```

Here is my Dockerfile:
```
FROM bitwalker/alpine-elixir-phoenix:6.1
LABEL name "sns_router"

# Set exposed ports
EXPOSE 5000
ENV PORT=5000 MIX_ENV=prod

# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

ADD . .

# Run compile
RUN mix do compile

CMD ["mix", "phoenix.server"]
```

Any idea how I could solve this issue ?
Thanks a lot in advance

**Comment by bitwalker** [comment]
Run `mix local.hex --force && mix local.rebar --force` in your Dockerfile, that will ensure hex and rebar are installed and up to date :)

**Comment by tlvenn** [comment]
Hi @bitwalker,

I should probably had mentioned that I had already tried that, same error happens...

**Comment by tlvenn** [comment]
I believe the root issue lies with your image using `default` user and when Zeit run the container the home dir is pointing at `root`.

**Comment by bitwalker** [comment]
@tlvenn I'll take a look and get a fix in place. Why does Zeit run the container as root? That may not be a question you can answer, but it's a dangerous configuration to use.

**Comment by Faolain** [comment]
Hey bitwalker great work, I have a related issue(possibly) but in this case using drone. Using the 
bitwalker/alpine-elixir-phoenix:2.0 image I don't have a problem(unfortunately my project fails to compile due to distillery's dependency on elixir 1.3) however when I use the latest alpine-elixir-phoenix image...I encounter the same error 

```Could not find Hex, which is needed to build dependency :phoenix```

I encounter this issue by similarly creating my own image based off of 

```FROM bitwalker/alpine-erlang:19.2.1b
# Install Elixir and basic build dependencies
RUN \
    echo "@edge http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk update && \
    apk --no-cache --update add \
      git make g++ \
      elixir@edge=1.4.2-r0 && \
    rm -rf /var/cache/apk/*

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force
```

Any ideas what could be causing this? For the latter image if I run mix hex.info it indeed shows hex is installed but on my drone server test it fails out with `Could not find Hex, which is needed to build dependency :phoenix`.

**Comment by bitwalker** [comment]
That sounds like a permissions thing to me - perhaps drone is changing the user of the image to non-root, and thus the new user doesn't have permissions to even see the hex binaries? That is definitely strange. I'm not sure what would cause this error though given what you've described :(

**Comment by Faolain** [comment]
Sigh :( thanks bitwalker. I'm not sure if this helps but I confirmed drone runs the container as root. (Even ran a whoami at the start of the build which says root). Anything else you could imagine as to why hex would not be present at the start of the build but present after running the commands within the container when it's instantiated? I guess what makes me think it has to do something with the dockerfile is that this issue doesn't happen with the older alpine-elixir-image. Is it possible the older version alpine-elixir-phoenix:2.0 had something that this doesn't in terms of configuration?
