### ISSUE TITLE
Update documention to provide multi-stage builds

### ISSUE THREAD

**Issue by Jesse-Cameron** [bitwalker/alpine-elixir-phoenix#42]
Hey!

I've been using your images for my own personal site for a while now. Real big fan.
Just wondering if you would be willing to accept contributions to this repo for documentation on how to use docker multistage builds.

Using this technique I managed to get my image size down by roughly 40%. But as always, YMMV.

Happy to put together a PR if you think this is valuable.

**Comment by bitwalker** [comment]
Sure, that'd be great!

**Comment by Jesse-Cameron** [comment]
Awesome check it out [here](https://github.com/bitwalker/alpine-elixir-phoenix/pull/44)

**Comment by bitwalker** [comment]
Closing via #44
