### ISSUE TITLE
Hex and Rebar installation

### ISSUE THREAD

**Issue by gabrielpra1** [bitwalker/alpine-elixir-phoenix#50]
Is there a specific reason for changing fro `RUN` to `ONBUILD RUN` in this last commit (https://github.com/bitwalker/alpine-elixir-phoenix/commit/50ec353ee29edae35fed20fafc5e76a4e5797f23)?

As I understand it, the `ONBUILD RUN` is only going to be executed when extending the image, but that's not my use case, I just use this image for my CI job that builds the release. And for that use case, this image no longer works out-of-the-box. So I'm wondering if that's intended?

**Comment by bitwalker** [comment]
Hex and Rebar are already installed in the base image, `alpine-elixir`, the `ONBUILD RUN` is there to ensure that those tools get updated when extending the image. Could you clarify the problem you are seeing with the latest image?

**Comment by gabrielpra1** [comment]
Ah, that makes sense! This is what I'm getting after updating the image:

```
Running with gitlab-runner 11.5.1 (7f00c780)
Using Docker executor with image bitwalker/alpine-elixir-phoenix:1.9.0.1.9 ...
Pulling docker image bitwalker/alpine-elixir-phoenix:1.9.0.1.9 ...
Using docker image sha256:d483d2c4c4ccc6f0cee2d9c87e3b24c4d366bb28616b32d38f0d47f9a18ab3e6 for bitwalker/alpine-elixir-phoenix:1.9.0.1.9 ...
Running on runner-tP2cCbeo-project-12906617-concurrent-1...

Cloning repository...

$ mix deps.get
Could not find Hex, which is needed to build dependency :phoenix
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :phoenix from Project.MixProject
```

**Comment by bitwalker** [comment]
I found the problem - this image sets `MIX_HOME` and `HEX_HOME`, but the base image doesn't, which results in the `hex` and `rebar` deps not being found here. I'm not sure exactly why those were added, but I suspect it was to keep them out of the app directory, so I've moved those env vars to the `alpine-elixir` image and rebuilt both that and this image, and updated the images on Docker Hub. Testing locally everything checks out, so you should be good to go!

**Comment by gabrielpra1** [comment]
Yep, working perfectly now, thank you!
