### ISSUE TITLE
Adding inotify-tools to the image

### ISSUE THREAD

**Issue by Nagasaki45** [bitwalker/alpine-elixir-phoenix#6]
When used in development the phoenix live reload depends on `inotifywait`. Will you consider adding it to the image?

```
RUN apk --no-cache add inotify-tools
```

**Comment by bitwalker** [comment]
Done :)

**Comment by Nagasaki45** [comment]
Hi @bitwalker, can you please link to where it was solved? I can't see any new commit in this repo nor in the base image repo (bitwalker/alpine-erlang).
Thanks!

**Comment by bitwalker** [comment]
Sorry forgot to push the code changes upstream. The updated version was on Docker Hub though.
