### ISSUE TITLE
Tag latest with 1.10.4?

### ISSUE THREAD

**Issue by wreppun** [bitwalker/alpine-elixir-phoenix#65]
First, thanks for maintaining these images!

Would it be possible to tag `latest` with `1.10.4` as well?  I'd like to pull the most recent update, but am always a little hesitant to pin to `latest`.

**Comment by frahugo** [comment]
+1

**Comment by frahugo** [comment]
@octosteve Would it be possible to do again a `make release` in order to have tag `1.10.4` on Docker Hub? Thanks. ;-)

**Comment by mchadwick** [comment]
+1

**Comment by ccapndave** [comment]
+1 - some kind of node problem has appeared with the latest `apk` packages for `1.10.2` and `1.10.3` which cause this error:

```
Error relocating /usr/bin/node: nghttp2_option_set_max_settings: symbol not found
```

The problem goes away with `alpine-elixir-1.10.4` so it would be really awesome to get a `1.10.4` release for this package too (we also aren't in a position to use `latest` yet).

**Comment by lpil** [comment]
Seems that 1.11.0 also is untagged, perhaps some automation has broken?

**Comment by bitwalker** [comment]
1.11.3 is tagged and released now
