### ISSUE TITLE
Remove deprecated image tags on Docker Hub

### ISSUE THREAD

**Issue by pehbehbeh** [bitwalker/alpine-elixir-phoenix#67]
We use Dependabot to do automatic pull requests for dependency updates. On Docker Hub there are 5 year old tags which are breaking Semantic Versioning. This makes it impossible to upgrade via Dependabot.

The tags are: `1.0`, `2.0`, `3.0`, `4.0`, `4.1`, `5.0`, `6.0`, `6.1`, `6.2`

Would it be possible to delete these tags?

### Dependabot example 

<img width="966" alt="Bildschirmfoto 2020-10-30 um 12 19 29" src="https://user-images.githubusercontent.com/133831/97699785-04f7a380-1aab-11eb-94be-c0ef1ebe422d.png">

**Comment by bitwalker** [comment]
Done
