### ISSUE TITLE
Switch to hexpm docker images

### ISSUE THREAD

**Issue by rupurt** [bitwalker/alpine-elixir-phoenix#70]
Hi :wave:,

The hexpm team has been publishing well maintained Elixir & Erlang docker images. How do you feel about switching to them instead of building custom images?

https://hub.docker.com/r/hexpm/elixir/tags?page=1&ordering=last_updated&name=alpine

**Comment by bitwalker** [comment]
I think that's perfectly fine to use those images in place of this one - I personally prefer to use images I control, but for others that just want an image which does Erlang/Elixir things, it makes sense to use "official" images. That said, I don't recall those images including things like Node and what not, but if they do, then I will probably stop maintaining _this_ image at least, the lower-level Erlang/Elixir images I'll continue to maintain for my own use.
