### ISSUE TITLE
New image for 1.12.3 and erlang 24.0.6

### ISSUE THREAD

**Issue by frahugo** [bitwalker/alpine-elixir-phoenix#74]
Hi @bitwalker . Would it be possible to generate a docker Hub image tagged with 1.12.3 so we can upgrade to OTP 24.0.6 and be ready for the root certificate issue on Sept. 30th?

Thanks a lot!

https://github.com/bitwalker/alpine-elixir/commit/6f060aee7a968bb02b2802dddb9503560ccaafd8

**Comment by zalam003** [comment]
@bitwalker I have updated the necessary files to be able to generate the docker hub image.
